export interface EventData {
  events: EventData[];
  id: number;
  event_id: string;
  task_category: string;
  utc_time: string;
  process_guid: string;
  process_id: number;
  image: string;
  user: string;
  // target_filename: string;
  // creation_utc_time: string;
  // previous_creation_utc_time: string;
  // query_name: string;
  // query_status: string;
  // query_results: string;
  // protocol: string;
  // initiated: boolean;
  // source_is_ipv6: boolean;
  // source_ip: string;
  // source_hostname: string;
  // source_port: number;
  // source_port_name: string;
  // destination_is_ipv6: boolean;
  // destination_ip: string;
  // destination_hostname: string;
  // destination_port: number;
  // destination_port_name: string;
  // file_version: string;
  // description: string;
  // product: string;
  // company: string;
  // original_file_name: string;
  // command_line: string;
  // current_directory: string;
  // logon_guid: string;
  // logon_id: string;
  // terminal_session_id: string;
  // integrity_level: string;
  // hashes_md5: string;
  // hashes_sha256: string;
  // hashes_imphash: string;
  // parent_process_guid: string;
  // parent_process_id: number;
  // parent_image: string;
  // parent_command_line: string;
  // parent_user: string;
  // target_object: string;
  // details: string;
  // is_passed_sigma_rules: boolean;
  // device: string;
}
